apiVersion: v1
kind: Namespace
metadata:
  name: nsx-demo-app
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    demo.openshift.io/owner: nsx-policy-demo
    demo.openshift.io/network: nsx-demo
    demo.openshift.io/role: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsx-demo-db
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    demo.openshift.io/owner: nsx-policy-demo
    demo.openshift.io/network: nsx-demo
    demo.openshift.io/role: db
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsx-demo-ops
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    demo.openshift.io/owner: nsx-policy-demo
    demo.openshift.io/network: nsx-demo
    demo.openshift.io/role: ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsx-demo-corp
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    demo.openshift.io/owner: nsx-policy-demo
    demo.openshift.io/network: nsx-demo
    demo.openshift.io/role: corporate
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsx-demo-rogue
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    demo.openshift.io/owner: nsx-policy-demo
    demo.openshift.io/network: nsx-demo
    demo.openshift.io/role: rogue
